version: "3.9"
services:            
    fileserver:
      hostname: simplefileserver
      image: kingtechnl/simplefileserver:alpha
      ports:
        - 8003:8080
        - 8004:443
      volumes:
        - ./Files:/files
        - ./Plugins/:/plugins
      environment:
        - Logging__LogLevel__Default=Debug
        - ENABLE_SWAGGER=true
        - PluginSettings__PluginDirectories=/plugins
        - FileSystemFileSourceSettings__BaseDirectory=/files
        - FileSystemFileSourceSettings__IsReadOnly=true
        - ImageResizeTransformerSettings__ThumbnailWidth=100
        - ImageResizeTransformerSettings__ThumbnailHeight=100
        - ImageResizeTransformerSettings__KeepThumbnailAspectRatio=true
        - Seq__Enabled=true
        - Seq__ServerUrl=host.docker.internal:5341
      networks:
        - betasite