#Dockerfile for simplefileserver image

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build
WORKDIR /src
COPY ["KingTech.Web.SimpleFileServer/KingTech.Web.SimpleFileServer.csproj", "KingTech.Web.SimpleFileServer/"]
COPY ["KingTech.Web.SimpleFileServer.Abstract.NuGet/KingTech.Web.SimpleFileServer.Abstract.NuGet.csproj", "KingTech.Web.SimpleFileServer.Abstract.NuGet/"]
#COPY ["./", "KingTech.Web.SimpleFileServer/"]
RUN dotnet restore "KingTech.Web.SimpleFileServer/KingTech.Web.SimpleFileServer.csproj"
COPY  ["KingTech.Web.SimpleFileServer/", "KingTech.Web.SimpleFileServer/"]
COPY  ["KingTech.Web.SimpleFileServer.Abstract.NuGet/", "KingTech.Web.SimpleFileServer.Abstract.NuGet/"]
WORKDIR "/src/KingTech.Web.SimpleFileServer.Abstract.NuGet"
RUN dotnet build "KingTech.Web.SimpleFileServer.Abstract.NuGet.csproj" -c Release -o /app/build
WORKDIR "/src/KingTech.Web.SimpleFileServer"
RUN dotnet build "KingTech.Web.SimpleFileServer.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "KingTech.Web.SimpleFileServer.csproj" -c Release -o /app/publish


# The final docker image
FROM base AS final
WORKDIR /app

# Set the user and group IDs of the host user
ARG USER_ID
ARG GROUP_ID

# Adding bash for easy debugging of docker container.
RUN apk add --no-cache bash 

# Create a new user inside the container with the same IDs as the host user
RUN addgroup --gid $GROUP_ID myuser && \
adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID myuser

# Give ownership of the working directory to the new user
RUN chown myuser:myuser /app

# Switch to the newly created user
USER myuser

# Add compiled & published web application
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "KingTech.Web.SimpleFileServer.dll"]