<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	  <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.12.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Graph" Version="5.56.0" />
    <PackageReference Include="Microsoft.Graph.Core" Version="3.1.15" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="KingTech.Web.SimpleFileServer.Abstract" Version="0.1.0-onedrive-source.44">
	    <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\KingTech.Web.SimpleFileServer.Abstract.NuGet\KingTech.Web.SimpleFileServer.Abstract.NuGet.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)'=='Debug'">
		<ItemGroup>
			<MySourceFiles Include="$(TargetDir)\**\*.*" Exclude="$(TargetDir)\ref\*.*" />
			<Runtimes Include="$(TargetDir)runtimes\**\*.*" Exclude="$(TargetDir)\ref\*.*" />
		</ItemGroup>

		<Copy SourceFiles="@(MySourceFiles)" DestinationFiles="@(MySourceFiles->'..\KingTech.Web.SimpleFileServer\$(OutDir)plugins\OneDrivePlugins\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="false" OverwriteReadOnlyFiles="true" />
		<Copy SourceFiles="@(Runtimes)" DestinationFiles="@(Runtimes->'..\KingTech.Web.SimpleFileServer\$(OutDir)plugins\OneDrivePlugins\runtimes\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="false" OverwriteReadOnlyFiles="true" />
	</Target>
</Project>
