name: .NET build pipeline

# Triggers
on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

#: Jobs to execute
jobs:
  ## Build all projects
  build:
    runs-on: ubuntu-latest

    steps:
    ### Checkout repo
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    ### Build and publish SimpleWebServer image to dockerhub
    - name: main action
      if: success()
      uses: gvdmeijde/githubactions/base-action@main
      with:
        docker_registry_username: "${{ secrets.DOCKERHUB_USERNAME }}"
        docker_registry_password: "${{ secrets.DOCKERHUB_TOKEN }}"
        docker_file: "Dockerfile_simplefileserver"
        docker_image_name: "simplefileserver"
        nuget_api_key: "${{ secrets.NUGETORG_TOKEN }}"